---
- name: Fetch Incident and Update Incident fields data from ServiceNow
  hosts: localhost
  gather_facts: yes
  vars:
    sys_id: "9f31a4ef1b7179d014a68518624bcb94"
    dop_url: "https://api.0bc7-dop.aws.cloud.airbus-v.corp/incident-business-service/incidents"
    company_name: "companyName=airbus&uuid=9b34865d-c063-4bac-9d9a-17f1a57e2897"

tasks:
    - block:
      - name: Update assigned_to and incident_state fields in ServiceNow Incident
              uri:
                url: "{{ dop_url }}/{{ sys_id }}?{{ company_name }}"
                method: PATCH
                body_format: json
                headers:
                  Accept: "application/json"
                  #Authorization: "Basic {{ encoded_credentials | string }}"
                  Authorization: "Bearer {{ pat_token }}"
                return_content: yes
                force_basic_auth: yes
                body:
                  work_notes: "{{ extracted_output }}"
              register: result

      - name: Api response after assigning the ticket to user name 
        debug:
          var: result

    - name: Log Output For Failure
            debug:
              msg: "Log : FAILED : Task {{ ansible_failed_task.name }} Failed and the ERROR: {{ ansible_failed_result }}"
            failed_when: True
